import React from 'react'
import { Roboto_Flex, Bai_Jamjuree } from 'next/font/google'

import './globals.css'

const roboto = Roboto_Flex({ subsets: ['latin'], variable: '--font-sans' })
const bai = Bai_Jamjuree({ subsets: ['latin'], weight: '700', variable: '--font-display' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${roboto.variable} ${bai.variable}`}>{children}</body>
    </html>
  )
}
